"""Initial migration

Revision ID: 11080a5198a7
Revises: 
Create Date: 2026-05-18 23:12:50.347917

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '11080a5198a7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('question',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('text', sa.String(length=500), nullable=False),
    sa.Column('option_a', sa.String(length=100), nullable=False),
    sa.Column('option_b', sa.String(length=100), nullable=False),
    sa.Column('option_c', sa.String(length=100), nullable=False),
    sa.Column('option_d', sa.String(length=100), nullable=False),
    sa.Column('correct_answer', sa.String(length=10), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=150), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('referral_code', sa.String(length=20), nullable=True),
    sa.Column('referred_by', sa.String(length=20), nullable=True),
    sa.Column('balance_usd', sa.Float(), nullable=True),
    sa.Column('chances', sa.Integer(), nullable=True),
    sa.Column('is_active_member', sa.Boolean(), nullable=True),
    sa.Column('whatsapp_number', sa.String(length=20), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('last_chance_reset', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('referral_code')
    )
    op.create_table('answered_question',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('answered_by_id', sa.Integer(), nullable=False),
    sa.Column('selected_answer', sa.String(length=70), nullable=False),
    sa.Column('is_correct', sa.Boolean(), nullable=False),
    sa.Column('answered_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['answered_by_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['question_id'], ['question.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('payout_request',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('amount_usd', sa.Float(), nullable=True),
    sa.Column('deduction_fee_usd', sa.Float(), nullable=True),
    sa.Column('net_amount_usd', sa.Float(), nullable=True),
    sa.Column('bank_name', sa.String(length=100), nullable=False),
    sa.Column('account_number', sa.String(length=20), nullable=False),
    sa.Column('account_name', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('recharge_card',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pin', sa.String(length=50), nullable=False),
    sa.Column('network', sa.String(length=20), nullable=True),
    sa.Column('amount', sa.Integer(), nullable=True),
    sa.Column('is_used', sa.Boolean(), nullable=True),
    sa.Column('winner_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['winner_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('pin')
    )
    op.create_table('referral_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('referrer_id', sa.Integer(), nullable=True),
    sa.Column('referred_user_id', sa.Integer(), nullable=True),
    sa.Column('earnings_usd', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['referred_user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['referrer_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('referral_history')
    op.drop_table('recharge_card')
    op.drop_table('payout_request')
    op.drop_table('answered_question')
    op.drop_table('user')
    op.drop_table('question')
    # ### end Alembic commands ###
