"""add payment transaction table

Revision ID: a3f9c2d81e04
Revises: f38d6a1bc2e9
Create Date: 2026-07-10 00:00:00.000000


"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a3f9c2d81e04'
down_revision = 'f38d6a1bc2e9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payment_transaction',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('paystack_reference', sa.String(length=100), nullable=False),
    sa.Column('amount_kobo', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('verified_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('paystack_reference')
    )
    op.create_index(
        op.f('ix_payment_transaction_paystack_reference'),
        'payment_transaction',
        ['paystack_reference'],
        unique=True
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f('ix_payment_transaction_paystack_reference'),
        table_name='payment_transaction'
    )
    op.drop_table('payment_transaction')
    # ### end Alembic commands ###
